import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next typescript</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <h1>Welecome to Next typescript Material-UI app</h1>
    </div>
  );
}
